Make Omaha build with latest WTL(v10)
W/o this, compile failed with "fatal error C1189: WTL requires WINVER >= 0x0501"
error. That means WTL doesn't support lower version than Windows XP.